services:
  - type: worker
    name: telegram-adbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1

