services:
  - type: web
    name: telegram-adbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: RENDER
        value: true

